#!/usr/bin/env python3
"""
Quick start guide for the CAD Work Tracker
"""

print("="*60)
print("🚀 CAD Work Tracker - Quick Start Guide")
print("="*60)
print()
print("📋 STEPS TO ACCESS ALL FEATURES:")
print()
print("1. 🌐 Open: http://127.0.0.1:5000")
print("2. 🔐 Click 'Admin Login'")
print("3. 👤 Username: mahesh.butani")
print("4. 🔑 Password: m.butani@321")
print("5. ✅ Login to access admin dashboard")
print()
print("📊 THEN YOU CAN ACCESS:")
print("   • Dashboard - Overview and charts")
print("   • Projects - Project management & analytics") 
print("   • Employees - Employee management & analytics")
print("   • Reports - CSV export & summary reports")
print("   • Database - Backup, export & cleanup tools")
print()
print("⚠️  IMPORTANT:")
print("   The Reports and Database pages require admin login!")
print("   If they appear blank, you need to login first.")
print()
print("💡 For Employee Access:")
print("   • Click 'Employee Login'")
print("   • Use: shaji, ibrahim, mohamed, etc.")
print("   • Password format: firstname@321")
print()
print("="*60)
print("🎯 All features are working - just login first!")
print("="*60)
